services:
  postgres:
    image: postgres:13-alpine
    container_name: seltra_postgres
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  algod:
    image: algorand/algod:latest
    container_name: seltra_algod
    ports:
      - "4001:8080"
      - "4002:7833"
    environment:
      - ALGORAND_DATA=/opt/algorand/node/data
    volumes:
      - algod_data:/opt/algorand/node/data
    command: ["goal", "node", "start", "-d", "/opt/algorand/node/data"]

  indexer:
    image: algorand/indexer:latest
    container_name: seltra_indexer
    ports:
      - "8980:8980"
    depends_on:
      - postgres
      - algod
    command: >
      algorand-indexer daemon 
      --postgres "postgresql://algorand:algorand@postgres:5432/indexer?sslmode=disable" 
      --algod-address "algod:8080" 
      --algod-token "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      --server "0.0.0.0:8980"

  market-simulator:
    build:
      context: .
      dockerfile: simulation/Dockerfile
    container_name: seltra_simulator
    ports:
      - "8000:8000"
    environment:
      - ALGORAND_ALGOD_ADDRESS=http://algod:8080
      - ALGORAND_ALGOD_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    depends_on:
      - algod
    volumes:
      - ./simulation:/app/simulation
      - ./contracts:/app/contracts

  # frontend:
  #   build: ./frontend
  #   container_name: seltra_frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_ALGOD_ADDRESS=http://localhost:4001
  #     - REACT_APP_ALGOD_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  #     - REACT_APP_SIMULATOR_ADDRESS=http://localhost:8001
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

  nextjs-frontend:
    build: ./nextjs-frontend
    container_name: seltra_nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_NETWORK=testnet
      - NEXT_PUBLIC_ALGOD_ADDRESS=https://testnet-api.algonode.cloud
      - NEXT_PUBLIC_ALGOD_TOKEN=
      - NEXT_PUBLIC_INDEXER_ADDRESS=https://testnet-idx.algonode.cloud
      - NEXT_PUBLIC_SELTRA_POOL_APP_ID=${SELTRA_POOL_APP_ID}
      - NEXT_PUBLIC_ASSET_X_ID=${ASSET_X_ID}
      - NEXT_PUBLIC_ASSET_Y_ID=${ASSET_Y_ID}
      - NEXT_PUBLIC_SIMULATOR_ADDRESS=http://localhost:8000
    volumes:
      - ./nextjs-frontend:/app
      - /app/node_modules
      - /app/.next

  dev-frontend:
    build: ./dev-frontend
    container_name: seltra_dev_frontend
    ports:
      - "3001:3001"
    environment:
      - VITE_SIMULATOR_URL=http://localhost:8001
    volumes:
      - ./dev-frontend:/app
      - /app/node_modules
    depends_on:
      - market-simulator

volumes:
  postgres_data:
  algod_data: