services:
  market-simulator:
    build:
      context: .
      dockerfile: simulation/Dockerfile
    container_name: seltra_simulator
    ports:
      - "8001:8000"
    environment:
      - ALGORAND_ALGOD_ADDRESS=http://localhost:4001
      - ALGORAND_ALGOD_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - ALGORAND_INDEXER_ADDRESS=http://localhost:8980
      - SELTRA_POOL_APP_ID=${SELTRA_POOL_APP_ID}
      - ASSET_X_ID=${ASSET_X_ID}
      - ASSET_Y_ID=${ASSET_Y_ID}
      - FAUCET_PRIVATE_KEY=${FAUCET_PRIVATE_KEY}
    network_mode: host
    volumes:
      - ./simulation:/app/simulation
      - ./contracts:/app/contracts

  frontend:
    build: ./frontend
    container_name: seltra_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_ALGOD_ADDRESS=http://localhost:4001
      - REACT_APP_ALGOD_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - REACT_APP_SIMULATOR_ADDRESS=http://localhost:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules

  dev-frontend:
    build: ./dev-frontend
    container_name: seltra_dev_frontend
    ports:
      - "3001:3001"
    environment:
      - VITE_SIMULATOR_URL=http://localhost:8001
      - VITE_ALGOD_ADDRESS=http://localhost:4001
      - VITE_ALGOD_TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - VITE_INDEXER_ADDRESS=http://localhost:8980
    volumes:
      - ./dev-frontend:/app
      - /app/node_modules
