services:
  # Simple Algorand Node for development
  algod:
    image: algorand/stable:latest
    container_name: seltra-algod-simple
    ports:
      - "0.0.0.0:4001:4001" # Algorand REST API (accessible via LAN)
    environment:
      - ALGORAND_NETWORK=devnet
      - ALGORAND_DATA=/opt/algorand/node/data
    volumes:
      - algod-data:/opt/algorand/node/data
    command: >
      sh -c "
        /opt/algorand/node/goal node start -d /opt/algorand/node/data &&
        tail -f /opt/algorand/node/data/node.log
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/v2/status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  algod-data:
    driver: local
